matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode9

notifications:
  email: false

before_install:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then
      sudo add-apt-repository -y ppa:beineri/opt-qt591-trusty;
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
      sudo apt-get update -y;
      sudo apt-get install -y g++-7 cmake clang libicu-dev;
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90;
      sudo update-alternatives --set g++ "/usr/bin/g++-7";
      sudo apt-get install -y qt59-meta-full;
      QT_ENV_SCRIPT=$(find /opt -name 'qt*-env.sh');
      source $QT_ENV_SCRIPT;
      wget https://swift.org/builds/swift-4.0-release/ubuntu1404/swift-4.0-RELEASE/swift-4.0-RELEASE-ubuntu14.04.tar.gz;
      tar xzvf swift-4.0-RELEASE-ubuntu14.04.tar.gz;
      export PATH=swift-4.0-RELEASE-ubuntu14.04/usr/bin:$PATH;
      export CC=/usr/bin/clang;
      export CXX=/usr/bin/clang;
    fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then
      brew install qt cmake;
    fi

script:
  - ./buildscript.sh

