matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode9

notifications:
  email: false

before_install:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then
      sudo add-apt-repository -y ppa:beineri/opt-qt591-trusty;
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
      wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -;
      sudo bash -c "echo \"deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.9 main\" >> /etc/apt/sources.list";
      sudo apt-get update -y;
      sudo apt-get install -y libbsd-dev cmake libicu-dev clang-3.9 lldb-3.9 g++-7;
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7;
      sudo update-alternatives --set g++ "/usr/bin/g++-7";
      sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-3.9 100;
      sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-3.9 100;
      sudo apt-get install -y qt59-meta-full;
      source /opt/qt59/bin/qt59-env.sh;
      sudo update-alternatives --install /usr/bin/ld ld /usr/bin/ld.bfd 10;
      sudo update-alternatives --install /usr/bin/ld ld /usr/bin/ld.gold 9;
      sudo update-alternatives --set ld /usr/bin/ld.gold;
      wget https://swift.org/builds/swift-4.0-release/ubuntu1404/swift-4.0-RELEASE/swift-4.0-RELEASE-ubuntu14.04.tar.gz;
      tar xzf swift-4.0-RELEASE-ubuntu14.04.tar.gz;
      rm -rf swift-4.0-RELEASE-ubuntu14.04.tar.gz;
      export PATH=$(pwd)/swift-4.0-RELEASE-ubuntu14.04/usr/bin:$PATH;
      git clone https://github.com/apple/swift-corelibs-libdispatch/;
      cd swift-corelibs-libdispatch;
      git checkout swift-4.0-branch;
      sh autogen.sh;
      ./configure --enable-static=yes --enable-shared=yes --with-swift-toolchain=$(pwd)/../swift-4.0-RELEASE-ubuntu14.04/usr --prefix=$(pwd)/../swift-4.0-RELEASE-ubuntu14.04/usr;
      make;
      make install;
      cd ../swift-4.0-RELEASE-ubuntu14.04/;
      cp usr/lib/swift/linux/libdispatch.la usr/lib/swift_static/linux/;
      cp usr/lib/swift/linux/libdispatch.a usr/lib/swift_static/linux/;
      cp usr/lib/swift/linux/x86_64/Dispatch.swiftdoc usr/lib/swift/pm/4/PackageDescription.swiftdoc;
      cd ..;
      rm -rf swift-corelibs-libdispatch;
      wget http://www.cmake.org/files/v3.5/cmake-3.5.2.tar.gz;
      tar xf cmake-3.5.2.tar.gz;
      cd cmake-3.5.2;
      ./configure;
      make;
      sudo make install;
      sudo update-alternatives --install /usr/bin/cmake cmake /usr/local/bin/cmake 1 --force;
      cd ..;
      rm -rf cmake-3.5.2.tar.gz cmake-3.5.2;
    fi

  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then
      brew install qt;
    fi

script:
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then
      ./buildscript.sh release;
    fi

  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then
      CC=gcc-7 CXX=g++-7 LIBRARY_PATH=/opt/qt59/lib ./buildscript.sh release;
    fi

