sudo: enabled
language: cpp
osx_image: xcode9
os:
  - osx

notifications:
  email: false

before_install:
 - if [[ $TRAVIS_OS_NAME == "osx" ]]; then
     brew install qt cmake;
     brew link qt --force;
   fi

script:
 - if [[ $TRAVIS_OS_NAME == "osx" ]]; then
    ./buildscript.sh;
   fi

